"""
SQLAlchemy model for the machining_plans table.
Owned exclusively by AI Service.
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import String, Float, DateTime, Text
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.orm import Mapped, mapped_column

from shared.db import Base


class MachiningPlan(Base):
    """
    Persisted machining plan generated by the rule engine.

    The full plan structure (setups, operations, tools) is stored as JSON
    in plan_data.  This keeps the table simple while still allowing SQL
    queries on model_id and estimated_time.
    """
    __tablename__ = "machining_plans"

    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
    )
    model_id: Mapped[str] = mapped_column(
        String(36),
        nullable=False,
        index=True,
        comment="FK to models.id (logical, not enforced — different service boundary)",
    )
    material: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
    )
    machine_type: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
    )
    plan_data: Mapped[dict] = mapped_column(
        JSON,
        nullable=False,
        default=dict,
        comment="Full MachiningPlanResponse serialised as JSON",
    )
    estimated_time: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        default=0.0,
        comment="Total estimated machining time in seconds",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    def __repr__(self) -> str:
        return (
            f"<MachiningPlan id={self.id} model_id={self.model_id} "
            f"machine={self.machine_type} time={self.estimated_time:.1f}s>"
        )
