"""
SQLAlchemy models for the AI Service.

  • MachiningPlan         — persisted machining plans (versioned)
  • FeatureValidationLog  — audit trail for feature validation calls
"""

import uuid
from datetime import datetime, timezone
from typing import Optional

from sqlalchemy import String, Float, Integer, Boolean, DateTime, Text
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.orm import Mapped, mapped_column

from shared.db import Base


class MachiningPlan(Base):
    """
    Persisted machining plan generated by the rule engine + LLM optimizer.

    The full plan structure (setups, operations, tools) is stored as JSON
    in plan_data.  This keeps the table simple while still allowing SQL
    queries on model_id, version, and estimated_time.
    """
    __tablename__ = "machining_plans"

    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
    )
    model_id: Mapped[str] = mapped_column(
        String(36),
        nullable=False,
        index=True,
        comment="FK to models.id (logical, not enforced — different service boundary)",
    )
    material: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
    )
    machine_type: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
    )
    plan_data: Mapped[dict] = mapped_column(
        JSON,
        nullable=False,
        default=dict,
        comment="Full MachiningPlanResponse serialised as JSON",
    )
    estimated_time: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        default=0.0,
        comment="Total estimated machining time in seconds",
    )
    version: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=1,
        comment="Plan version — incremented on re-generation",
    )
    approved: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        comment="Human approval flag — always False on creation",
    )
    approved_by: Mapped[Optional[str]] = mapped_column(
        String(36),
        nullable=True,
        default=None,
        comment="User ID who approved (nullable until approved)",
    )
    approved_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
        comment="Timestamp of approval (nullable until approved)",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    def __repr__(self) -> str:
        return (
            f"<MachiningPlan id={self.id} model_id={self.model_id} "
            f"v={self.version} approved={self.approved} "
            f"machine={self.machine_type} time={self.estimated_time:.1f}s>"
        )


class FeatureValidationLog(Base):
    """
    Audit trail for feature validation calls.

    Stores raw vs validated features + geometry snapshot.
    Used for:
        • Debugging validation decisions
        • Training data for future ML validators
        • Compliance / audit
    """
    __tablename__ = "feature_validation_logs"

    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
    )
    model_id: Mapped[str] = mapped_column(
        String(36),
        nullable=False,
        index=True,
    )
    raw_features: Mapped[dict] = mapped_column(
        JSON,
        nullable=False,
        default=list,
        comment="Features as received from model_features table",
    )
    validated_features: Mapped[dict] = mapped_column(
        JSON,
        nullable=False,
        default=list,
        comment="Features after validation pass",
    )
    geometry_snapshot: Mapped[dict] = mapped_column(
        JSON,
        nullable=False,
        default=dict,
        comment="Geometry metrics at validation time",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    def __repr__(self) -> str:
        return (
            f"<FeatureValidationLog id={self.id} model_id={self.model_id}>"
        )


class PlanFeedback(Base):
    """
    Immutable audit record of every human edit to a machining plan.

    Links the original plan version to the new version and stores a
    structured diff for ML training and compliance auditing.
    """
    __tablename__ = "plan_feedback"

    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
    )
    plan_id: Mapped[str] = mapped_column(
        String(36),
        nullable=False,
        index=True,
        comment="ID of the ORIGINAL plan that was edited",
    )
    new_plan_id: Mapped[str] = mapped_column(
        String(36),
        nullable=False,
        comment="ID of the NEW plan version created by the edit",
    )
    original_plan: Mapped[dict] = mapped_column(
        JSON,
        nullable=False,
        comment="Snapshot of original plan_data before edit",
    )
    edited_plan: Mapped[dict] = mapped_column(
        JSON,
        nullable=False,
        comment="The edited plan_data submitted by the user",
    )
    diff: Mapped[dict] = mapped_column(
        JSON,
        nullable=False,
        comment="Structured diff: ops added/removed, tools/setups/order changed",
    )
    edited_by: Mapped[str] = mapped_column(
        String(36),
        nullable=False,
        comment="User ID who made the edit",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    def __repr__(self) -> str:
        return (
            f"<PlanFeedback id={self.id} plan={self.plan_id} → "
            f"new={self.new_plan_id} by={self.edited_by}>"
        )
